
privateKey: "-----BEGIN EC PRIVATE KEY-----\n\
MHcCAQEEIMwZD9nkierXck0Mei9vfMRj26OsfOwWCpCGkE1Y8YDZoAoGCCqGSM49\n\
AwEHoUQDQgAE9WXZDcD0ujoVPp7d6L89q9Ll/g6600nh/MgHY2QOzNGr9U9meEI5\n\
7xWBFEXp/vbW+Vv8/cDMucrY9FI301Jb+A==\n\
-----END EC PRIVATE KEY-----"
